sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t rc/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rc/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucker_name: "elasticbeanstalk-eu-central-1-164377939790"
    bucker_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY        